### ISSUE TITLE
CHUTE_ENABLED misspelled

### ISSUE THREAD

**Issue by SkiTiSu** [diydrones/ardupilot-wiki-issue-tracker#110]
Hi, I'm trying to crate MP UI for Parachute and I found CHUTE_ENABLED misspelled to CHUTE_ENABLE in http://copter.ardupilot.com/wiki/common-optional-hardware/parachute/ .

Thanks.

**Comment by rmackay9** [comment]
fixed, thanks!

**Comment by hamishwillee** [comment]
@rmackay9 Thanks Randy, you beat me to it!
