### ISSUE TITLE
Rover:  Have a separate topic for connecting escs and motors

### ISSUE THREAD

**Issue by gmorph** [diydrones/ardupilot-wiki-issue-tracker#116]
Want to cover things like braking and motor efficiency at low speed.

As reference, we have [this document on the topic for copter](http://copter.ardupilot.com/wiki/initial-setup/assembly-instructions/connect-escs-and-motors-pixhawk/).

This item spawned off #111

**Comment by hamishwillee** [comment]
@gmorph Given we do not have the expertise, I have asked for help on the [arduwiki editors group here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ardu-wiki-editors/F_ijgp4-Zc0/ZutiTS-kBAAJ).

**Comment by hamishwillee** [comment]
It seems most users set up escs and motors on their frames as provided by manufacturer. Therefore there isn't much point creating this topic.
