### ISSUE TITLE
Make copter doc "Magnetic Interference" common.

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/ardupilot-wiki-issue-tracker#129]
Make [Magnetic Interference](http://copter.ardupilot.com/wiki/common-appendix/automatic-compass-declination/) document "common" and add into "Advanced Configuration" section

**Comment by hamishwillee** [comment]
@gmorph [Magnetic Interference](http://copter.ardupilot.com/wiki/common-advanced-configuration/common-magnetic-interference/) is now common and in Advanced Configuration on all wikis (note that the link here is changed!).

I gave it a basic "tidy up" to fix some of the text and make it more generic. Would appreciate your "quick scan".

Closing!

**Comment by gmorph** [comment]
Scanned and it looks good.  Thanks Hamish.

Thanks, Grant.

On 17 August 2015 at 11:50, Hamish Willee <notifications@github.com> wrote:

> @gmorph <https://github.com/gmorph> Magnetic Interference
> <http://copter.ardupilot.com/wiki/common-advanced-configuration/common-magnetic-interference/>
> is now common and in Advanced Configuration on all wikis (note that the
> link here is changed!).
>
> I gave it a basic "tidy up" to fix some of the text and make it more
> generic. Would appreciate your "quick scan".
>
> Closing!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/diydrones/ardupilot-wiki-issue-tracker/issues/129#issuecomment-131652147>
> .
>



-- 
Thanks

Grant
