### ISSUE TITLE
Split Flight modes docs for Rover/Plane into individual sections

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/ardupilot-wiki-issue-tracker#130]
Ie make each mode document individual, like copters are.

**Comment by hamishwillee** [comment]
@gmorph You can see the starting point of this for planes below [Flight Modes](http://plane.ardupilot.com/wiki/flying/flight-modes/). I will have to tidy up some inter topic linking.

**Comment by gmorph** [comment]
That looks great Hamish.

On 25 August 2015 at 17:41, Hamish Willee <notifications@github.com> wrote:

> @gmorph <https://github.com/gmorph> You can see the starting point of
> this for planes below Flight Modes
> <http://plane.ardupilot.com/wiki/flying/flight-modes/>. I will have to
> tidy up some inter topic linking.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/diydrones/ardupilot-wiki-issue-tracker/issues/130#issuecomment-134512078>
> .
>



-- 
Thanks

Grant

**Comment by hamishwillee** [comment]
Great. Plane now done. I'll look at Rover later.

**Comment by hamishwillee** [comment]
@gmorph Rover done now too - you can see the links from http://rover.ardupilot.com/wiki/rover-control-modes/

Marking this as closed.
