### ISSUE TITLE
Should have a question mark in title

### ISSUE THREAD

**Issue by zlite** [diydrones/ardupilot-wiki-issue-tracker#132]
"What is a MultiCopter and How Does it Work" title should end with a question mark

http://copter.ardupilot.com/wiki/introduction/what-is-a-multicopter-and-how-does-it-work/

**Comment by hamishwillee** [comment]
Fixed. I also added a few links and made the videos larger (need to do this globally - #134).

I kind of consider question marks in titles as optional. Probably because I spent a lot of time on mediawiki where the title defines the URL, and ? was not supported in titles.

Thanks for posting.
