### ISSUE TITLE
Mavproxy Installation Instructions Modification

### ISSUE THREAD

**Issue by dellarb** [diydrones/ardupilot-wiki-issue-tracker#135]
I've noticed that the default set of packages listed to install on Linux for MavProxy doesn't include python-dev which is required for some systems (raspberry pi at a minimum)

Suggest it gets added to the list of packages to apt-get install alongside the existing ones so that people don't miss out.

Cheers
Ben

**Comment by hamishwillee** [comment]
Thanks Ben. I'm closing as I cross posted this to the MAVProxy repo https://github.com/Dronecode/MAVProxy/issues/190
