### ISSUE TITLE
Tutorial videos coming up as private (plane)

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/ardupilot-wiki-issue-tracker#14]
All but two of these videos are coming up as private on YouTube: http://plane.ardupilot.com/wiki/videoguides/

(originally posted here: http://ardupilot.com/forum/viewtopic.php?f=51&t=4704 )

**Comment by hamishwillee** [comment]
Closing. The private videos cannot be made public because no one owns them. I have therefore deleted them and replaced with a better set.

**Comment by sediq-khan** [comment]
Hi,
The link to the videos is not available, could you please let me know where can I find the Videos. On a separate note, I am adding a new message to the MAVLink list of messages, and want to display it on the Mission Planner,  I would appreciate your insight/advice on how to add the message and how to display it on the mission planner.

Thank you
