### ISSUE TITLE
How to use the “auth” command to sign a Pixhawk Board with your Certificate of Authenticity

### ISSUE THREAD

**Issue by ausi1972** [diydrones/ardupilot-wiki-issue-tracker#140]
[How to use the “auth” command to sign a Pixhawk Board with your Certificate of Authenticity](http://dev.ardupilot.com/wiki/how-to-use-the-auth-command-to-sign-a-pixhawk-board-with-your-certificate-of-authenticity/) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant

Is the AUTH command still present in any of the builds?
Which make version is needed to get the AUTH command to sign a COA onto a board?

**Comment by CraigElder** [comment]
Please send a message to celder@dronecode.org
