### ISSUE TITLE
Plane Parameters

### ISSUE THREAD

**Issue by badwan** [diydrones/ardupilot-wiki-issue-tracker#145]
Hi all 
This is my first participate, 
I have question could I get from Mission Planner the deflection values of rudder, aileron , elevator and throttle for all time of the flaying  .If yes what is the name of these parameters.
please note I have Apm 2.6.

[Plane Parameters](http://plane.ardupilot.com/wiki/arduplane-parameters/) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant

**Comment by hamishwillee** [comment]
Hi @badwan 

This Github repo is for "Issues and suggestions".

If you want technical support and questions (which is what I believe your request to be), please see the APM forums. In this case you want to look at [the Mission Planner forum](http://ardupilot.com/forum/viewforum.php?f=12&sid=ffdce0381eedc745045816c07377af12)

I am closing this post. Good luck with your flying!

Regards
Hamish
