### ISSUE TITLE
Inconsistencies in the ArduPlane arming documentation

### ISSUE THREAD

**Issue by Georacer** [diydrones/ardupilot-wiki-issue-tracker#148]
Naturally, there is a wiki page for Arming setup instructions: http://plane.ardupilot.com/wiki/arming-throttle/

As we all know, this involves a few parameters, some of which are the `REQUIRE`, `CHECK` etc.
However, none of these parameters are shown in the Parameter list: http://plane.ardupilot.com/wiki/arduplane-parameters/#eeprom_format_version_number_arduplaneformat_version, expect for the `ARMING_RUDDER` parameter which is not documented in the previous page.

Has the code been updated?

Thanks.

**Comment by gmorph** [comment]
Yes I have changed the code recently and I must of broken the doco.  Sorry.  I'll fix it now.  Great catch - thanks!

**Comment by gmorph** [comment]
Fixed by this PR
https://github.com/diydrones/ardupilot/pull/2852
Thanks - keep them coming!
