### ISSUE TITLE
Parameter description typo

### ISSUE THREAD

**Issue by Georacer** [diydrones/ardupilot-wiki-issue-tracker#152]
Minimum speed (STEER2SRV_MINSPD)

This is the minimum assumed ground speed in meters/second for steering. Having a minimum speed prevents oscillations when the vehicle first starts moving. The vehicle can still ~~driver~~ **drive** slower than this limit, but the steering calculations will be done based on this minimum speed.

**Comment by gmorph** [comment]
Fixed with this PR
https://github.com/diydrones/ardupilot/pull/2856
Thanks!
