### ISSUE TITLE
common-Planning a Mission with Waypoints and Events

### ISSUE THREAD

**Issue by Flavio-da-Brescia** [diydrones/ardupilot-wiki-issue-tracker#162]
[common-Planning a Mission with Waypoints and Events](http://plane.ardupilot.com/wiki/common-planning-a-mission-with-waypoints-and-events/) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant

Hello! I am running lubuntu and APM 2.0. I can save waypoint files, but when i try to open them, they don't show up in the folder. They are txt files like this:

QGC WPL 110
0	1	0	16	0	5	0	0	52.4024188739733177	4.8779296875	0	1
1	0	3	16	0	5	0	0	45.4755402715859205	10.2777099609375	20	1
2	0	3	16	0	5	0	0	45.8900081586618285	10.3656005859375	20	1
3	0	3	16	0	5	0	0	45.9396907823399943	10.7501220703125	20	1

**Comment by hamishwillee** [comment]
Hi Flavio, 

> I can save waypoint files, but when i try to open them, they don't show up in the folder. They are txt files like this:

I think what you are saying is that when you press the **Write WPs** button on Mission Planner the current set of WPs are written to a .txt file with the format you had above (you can see them in the file system). But if you select **Read WPs** the missions that you saved don't show up. 

Is that correct? If so, the best place to report this bug would be on the [Mission Planner](https://github.com/diydrones/MissionPlanner/issues) repo. I would also include the version of Lubuntu and Mission Planner you are using.

Regards
H

PS This repo is for bugs and suggestions for the documentation. The best place to ask questions/technical support is the [APM forum](http://ardupilot.com/forum/).
