### ISSUE TITLE
H-Frame settings seems to send the vehicle in the wrong heading

### ISSUE THREAD

**Issue by piningforfjords** [diydrones/ardupilot-wiki-issue-tracker#163]
Recently changed the settings, esc rotation and prop location from an X config to an H config.  The vehicle has an H frame.  Heading in mission planner appears to be 180 degrees out and with flight plans the vehicle goes in opposite direction.

**Comment by piningforfjords** [comment]
Code is 3.2

**Comment by hamishwillee** [comment]
Hi @piningforfjords 

The best place to ask for technical support about a particular configuration is the [APM Forums](http://ardupilot.com/forum/) - this will get a lot more people looking at your question.

This github area is more for highlighting a specific issue with the documentation or wiki.

Regards
Hamish
