### ISSUE TITLE
common-UBlox GPS Configuration - Corrupter configuration file (3DR-Ublox.txt) in line 4: 1

### ISSUE THREAD

**Issue by OG-BlaZeD** [diydrones/ardupilot-wiki-issue-tracker#164]
[common-UBlox GPS Configuration](http://copter.ardupilot.com/wiki/common-ublox-gps/) 

I'm trying to flash a Ublox H-8123 with U-Studio (v8.18) and I keep getting an error message: "Corrupted configuration file in Line 4: 1. Unable to store configuration to GPS receiver".  

I'm using an FTDI cable and I'm able to read data from the Ublox but I am unable to configure it (File > GNSS) since it keeps telling me the file is corrupted.  I'm unable to upload the "3DR-Ublox.txt" file but I found it here: https://github.com/diydrones/ardupilot/tree/master/libraries/AP_GPS/config

Thanks!

**Comment by hamishwillee** [comment]
Hi @OG-BlaZeD 

We try to keep this section for bugs and improvement suggestions about the content. If you want technical support, the best place to ask questions is the [APM Forums](http://ardupilot.com/forum/).

That said, there was a similar [post here on corrupted files](http://diydrones.com/forum/topics/apm-2-5-with-neo-6m-ublox-gps-not-3dr-lea-6?commentId=705844%3AComment%3A1930310), which might help.

Closing - thanks!

Regards
Hamish
