### ISSUE TITLE
RC Transmitter Flight Mode Configuration - FS-T6

### ISSUE THREAD

**Issue by kwh5ye** [diydrones/ardupilot-wiki-issue-tracker#165]
[common-RC Transmitter Flight Mode Configuration](http://copter.ardupilot.com/wiki/common-rc-transmitter-flight-mode-configuration/) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant

Does anyone have simple step by step instructions for programming FS-T6 controller to work with APM planner and Erle Copter? 

Cheers!

**Comment by hamishwillee** [comment]
@kwh5ye This is not the right place for general technical support. Raise those questions on the APM forums.

**Comment by kwh5ye** [comment]
Whoops! My apologies, I will ask there. Thank you for letting me know!
