### ISSUE TITLE
CoaxCopter Firmware

### ISSUE THREAD

**Issue by jparnesr** [diydrones/ardupilot-wiki-issue-tracker#169]
Hi, I just want to know if is the firmware available anywhere to use it. I've read in this link : 

http://copter.ardupilot.com/wiki/singlecopter-and-coaxcopter/ 

That I have to compile the source code, ¿What does it mean? I'm new at designing copters, so any help, suggestion will be great help. 

Thanks

**Comment by hamishwillee** [comment]
Hi @jparnesr 

As the  [documentation says](http://copter.ardupilot.com/wiki/singlecopter-and-coaxcopter/#load_the_firmware) you need to build the firmware. 

> What does it mean? 

Basically applications are written in high-level programming languages like C, C++, Python - this is called the "source code". Compiling/building a program is where you run tools over the source code to turn it into a binary format that computers can execute. The firmware is the compiled set of sources that make up ArduPilot. 

YOu can find out how to [build the source here](http://dev.ardupilot.com/wiki/building-the-code/). The "changes" you need to make to get this "generic" source to build for single copter are listed in [documentation says](http://copter.ardupilot.com/wiki/singlecopter-and-coaxcopter/#load_the_firmware)

In general, if you don't have a specific problem with the docs or suggestion then the post counts as a "support request". Best to post those on the APM forums.

I'm closing this now.

Regards
Hamish
