### ISSUE TITLE
Setting up SITL on Windows - change to Cygwin list

### ISSUE THREAD

**Issue by umfundi** [diydrones/ardupilot-wiki-issue-tracker#174]
[Setting up SITL on Windows](http://dev.ardupilot.com/wiki/sitl-native-on-windows/#install_cygwin) - 

Suggest changing the list of options to be installed to the following simply because it is in sorted order as it appears in the CygWin selection panel and saves jumping around selecting options:

package        |section                       |description
autoconf	     |Devel 				| autoconf: Wrapper scripts for autoconf commands
automake	    | Devel 				| automake: Wrapper scripts for automake and aclocal
ccache	    | Devel 				| ccache: A C compiler cache for improving recompilation
g++              | Devel 				| gcc-g++ GNU Compiler Collection (C++)
git                | Devel 				| git: Distributed version control system
libtool          | Devel 				| libtool: Generic library support script
make           | Devel 				| make: The GNU version of the ‘make’ utility
gawk           | Interpreters                 | gawk: GNU awk, a pattern scanning and processing language
libexpat       | Libs 				| libexpat-devel: Expat XML parswer library (development files)
procps	   | System 		        | procps: System and process monitoring utilities (required for pkill)

**Comment by hamishwillee** [comment]
@umfundi Thanks for your suggestion - I have [made the change](http://dev.ardupilot.com/wiki/sitl-native-on-windows/#install_cygwin). FYI I didn't do this previously because I search individually for every component rather than navigate the sections. 

Cheers
