### ISSUE TITLE
Accelerometer Calibration with high baud rates fails [AC3.3]

### ISSUE THREAD

**Issue by andersonpaac** [diydrones/ardupilot-wiki-issue-tracker#176]
AC 3.3 running on a quad X configuration.
Connected via USB at 1500000 baud rate on Mission Planner (windows - 1.3.32 latest).

Calibration fails upon hitting click when done.

>>Calibration started
>>Place vehicle level and press any key
            key pressed
>>Calibration Failed

**Comment by hamishwillee** [comment]
HI Anderson

This area is for posting bug reports and suggestion improvements about the documents and this is a technical support query that could be related to either Copter or Mission Planner. 

The right place to post this is the  [APM forums](http://ardupilot.com/forum/) - can you please repost in the appropriate forum?
