### ISSUE TITLE
Sonar Parameter Tuning

### ISSUE THREAD

**Issue by zhangjinming** [diydrones/ardupilot-wiki-issue-tracker#177]
[Sonar Parameter Tuning](http://rover.ardupilot.com/wiki/sonar-parameter-tuning/) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant

**Comment by rmackay9** [comment]
I think this page is more about sonar "configuration" rather than "tuning".

**Comment by hamishwillee** [comment]
@rmackay9 Do you want me to rename it "Sonar Parameter Tuning"? Otherwise I'm just going to close this as invalid.

**Comment by hamishwillee** [comment]
The most important Sonar parameters are set in the "Basic Tuning" page referred to. I suspect that people searching will therefore look for tuning.

Closing/leaving as is.
