### ISSUE TITLE
Continuous Pan Servo Support

### ISSUE THREAD

**Issue by artemen** [diydrones/ardupilot-wiki-issue-tracker#178]
Continuous Pan Servos are expensive, however almost ANY regular servo can be EASILY, WITHOUT soldering gun/ programmer modified for continuous rotation use. Please, add such support at least for APM/Pixhawk based tracker. 
https://www.youtube.com/watch?v=XUm2nj7te8E

**Comment by hamishwillee** [comment]
This is primarily a hardware hack - nothing to do with software. There isn't anything particularly relevant to ardupilot here and certainly not something for the wiki.

**Comment by artemen** [comment]
Hamish, with all respect you didn't underatand the request: add continuous pan servo support to Antenna Tracker firmware for APM/Pixhawk. 
Please reopen this issue as this is certanly a valid request.

**Comment by hamishwillee** [comment]
Hi @artemen 

Thanks - can you please repost this request in [the ArduPilot issue tracker](https://github.com/diydrones/ardupilot/issues) (this issue tracker is for improvements to the wiki infrastructure and content - not to the autopilot itself).

**Comment by artemen** [comment]
Done. Thx!
