### ISSUE TITLE
Windows APM build pages need technical review

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/ardupilot-wiki-issue-tracker#179]
These are the relevant sections:

* [Building ArduPilot for APM2.x on Windows with Arduino](http://dev.ardupilot.com/wiki/building-ardupilot-with-arduino-windows/)
* [Building ArduPilot for APM2.x with Make](http://dev.ardupilot.com/wiki/building_with_make/#windows)
  * [Building ArduPilot for APM2.x on Windows with Make](http://dev.ardupilot.com/wiki/building-ardupilot-for-apm2-x-on-windows-with-make/)

The equivalent "Eclipse" documents should also be reviewed - e.g. [Building ArduPilot for APM2.x with Eclipse on Windows](http://dev.ardupilot.com/wiki/building-apm2-with-eclipse-on-windows/)

**Comment by gmorph** [comment]
Looks fine.

**Comment by hamishwillee** [comment]
Thanks Grant!
