### ISSUE TITLE
Parameter Reset

### ISSUE THREAD

**Issue by AlencarPacheco** [diydrones/ardupilot-wiki-issue-tracker#184]
Hello when I trigger the lever channel 5 the same command channel 6?!?
How do I return to the previous, ie want to drive the 5 channel again!

**Comment by rmackay9** [comment]
This looks like a flight controller request.  If it's a support issue it should go into the APM:Forum.
http://ardupilot.com/forum/index.php

If it's an enhancement request it should go into the ardupilot issues list.
https://github.com/diydrones/ardupilot/issues
