### ISSUE TITLE
Crash - unexpected perfect fast roll rotations straight to the ground on RTL

### ISSUE THREAD

**Issue by egzumer** [diydrones/ardupilot-wiki-issue-tracker#192]
I had a crash lately. I have some trouble with my GPS, it looses fix for some reason. I believe the crash happened right after I tried to switch RTL which I have setup under channel 7. I switched it once, but it didn't react as the GPS had no fix. I switched it of and on again, and it did couple of roll rotations (3-5) straight to the ground. I tried to switch modes when it was falling but it didn't react anyhow. The rotations were consistent, fast with the axis of rotation right in the middle of the quadcopter from left to right, it looked like it was doing what the ecu wanted it to do. It didn't look like ESC/motor failure. After crash I mounted new props and it flies just fine now. In logs it shows desired roll of 230 degrees so it looks like some ECU error. 
I'm glad I didn't mount camera gimbal yet. Now I'm afraid to do so.

The log:
https://www.dropbox.com/s/ck92reckfmbnuao/2015-10-24%2012-45-38.bin?dl=0

**Comment by hamishwillee** [comment]
Hi @egzumer 

We use github for documentation bugs/feedback. For technical support, please go to the [APM forums](http://ardupilot.com/forum/).
