### ISSUE TITLE
Adding the step on the page of "Adding a New Flight Mode"

### ISSUE THREAD

**Issue by zxc2694** [diydrones/ardupilot-wiki-issue-tracker#196]
We need to add the step, because the console appears the error message after i finished all steps and compiling.
The step is that add two lines "XXX_init(bool ignore_checks);" and "void XXX_run();" in the [Copter.h](https://github.com/diydrones/ardupilot/blob/master/ArduCopter/Copter.h)
(Maybe XXX is "newflightmode").

[Adding a New Flight Mode (Copter Code Overview)](http://dev.ardupilot.com/wiki/apmcopter-adding-a-new-flight-mode/)

**Comment by hamishwillee** [comment]
Thanks @zxc2694 !

@rmackay9 @gmorph In the instructions [Adding a New Flight Mode (Copter Code Overview)](http://dev.ardupilot.com/wiki/apmcopter-adding-a-new-flight-mode/) (Step2) we define some  _init and _run methods, but do not declare them. All the other modes do the same thing but declare the methods in copter.h. 

Can you confirm that a step to add these methods for a new mode is needed?

**Comment by zxc2694** [comment]
Hi @hamishwillee , 
I have confirmed. The project which is added new mode can be compiled successfully when i declared the methods in copter.h.

**Comment by hamishwillee** [comment]
I've updated [Adding a New Flight Mode (Copter Code Overview)](http://dev.ardupilot.com/wiki/apmcopter-adding-a-new-flight-mode/) with (new) step 3 as shown below.
![image](https://cloud.githubusercontent.com/assets/5368500/10808654/fb683be6-7e41-11e5-974f-ba816dcbfab8.png)

Closing this issue now.

Thanks @zxc2694 !
