### ISSUE TITLE
Building ArduPilot for Pixhawk/PX4 on Windows with Make

### ISSUE THREAD

**Issue by dornoti** [diydrones/ardupilot-wiki-issue-tracker#201]
Hello!
When I am following this guide (http://dev.ardupilot.com/wiki/building-px4-with-make/) and trying to "make" px4-v2, I get an error:

../mk/find_tools.mk:67: *** ERROR cannot find the compiler tools for AVR anywhere on the path

What to do?!?!

Thank you

**Comment by hamishwillee** [comment]
Did you install the tools in step 4?

**Comment by hamishwillee** [comment]
I have just retested the instructions on a clean Windows 10 machine. They work as stated. I am therefore closing as "Invalid"
