### ISSUE TITLE
Add clones to wiki

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot-wiki-issue-tracker#202]
We should add a list of readily available pixhawk clones to the wiki including:
1. where they can be purchased
2. their available features
3. whether design schematics are available or not
4. recommended or not, known problems, etc

**Comment by hamishwillee** [comment]
Happy to do so. I think we discussed this previously and decided that we'd only have dronecode members, and by implication, only those with published schematics etc.

@CraigElder @rmackay9 Did you have a "seed list" of such manufacturers/boards? I can probably pull a lot of the other information together once I have a set of names/urls for purchasing the products. If not I can search and present initial list to you.

**Comment by CraigElder** [comment]
We have the list of boards that support the project and the boards supported by the project here. http://dev.ardupilot.com/wiki/supported-autopilot-controller-boards/.

**Comment by hamishwillee** [comment]
That is true - after all, I created it :-) @rmackay9 Are there other "clones"/information you were expecting?
Not all of these have schematics (or at least I couldn't find them last time I looked)

**Comment by CraigElder** [comment]
The supported ones have schematics and are open source

**Comment by hamishwillee** [comment]
@rmackay9 Closing this then - please reopen if you see a board missing or know if any other issues/known problems that could be added.
