### ISSUE TITLE
Electronic Speed Controller (ESC) Calibration

### ISSUE THREAD

**Issue by bkeeber** [diydrones/ardupilot-wiki-issue-tracker#204]
[Electronic Speed Controller (ESC) Calibration](http://copter.ardupilot.com/wiki/esc-calibration/) -
To whom it may concern, 

Hi all. I recently went through the ESC Calibration steps with my PX4FMU (https://pixhawk.org/modules/px4fmu) and 4 RCTimer 12A ESCs running SimonK firmware(http://rctimer.com/product-1134.html). 

I was attempting the all-at-once calibration method, which failed. I then proceeded to manually calibrate the ESCs individually, which was successful. When I reconnected everything however, I found that the PX4FMU was unresponsive. It now will not even register as a device when connected via USB. When powered on via either LiPO or USB, a solid green LED shines. 

I believe that I may have made the mistake of leaving the board plugged in to my laptop via USB while attempting all-at-once calibration, despite the instructional webpage explicitly warning against this. 

Did I completely fry the board, or is it bricked and able to be repaired? And if so, how can that be done?

If this question has already been asked in the APM forum, I was unable to find it and apologize. If you could link me to the specific discussion page I would be very grateful.

Thank you for your time.

**Comment by hamishwillee** [comment]
@bkeeber This forum is for reporting issues with the documentation, while your question is actually a technical support issue. Can you please repost on the APM forum - as that will get more knowledgable people helping you!

(if it is a duplicate the community will point you to the right direction !)
