### ISSUE TITLE
Google Earth December 2015 // Mission planner

### ISSUE THREAD

**Issue by zenyo9** [diydrones/ardupilot-wiki-issue-tracker#209]
Hi,

On December 12, 2015, Google will stop supporting Google Earth.
The main WMS on MP is google earth..
Are you planning to replace Google Earth by another WMS or just to stop with Google earth?

ty

**Comment by rmackay9** [comment]
This probably belongs in the mission planner issues list.  Any chance you could re-post over there?  Michael Oborne is more likely to see it there than here.
https://github.com/diydrones/MissionPlanner/issues
