### ISSUE TITLE
Lidar-Lite wiki: we should add info re the cap that goes between VCC and GND

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot-wiki-issue-tracker#21]
There's a discussion on diydrones about the exact cap that should be used.  I think Philip, Chris Anderson and Tridge all know which cap should be used.

**Comment by rmackay9** [comment]
Note, there's a discussion here on diydrones where Sandy asks for this.  
http://diydrones.com/profiles/blogs/cheap-ir-lidar-lite-90

**Comment by hamishwillee** [comment]
Page updated with new image.

**Comment by rmackay9** [comment]
hmm.. I don't see the cap in that diagram...

**Comment by rmackay9** [comment]
Ah, sorry, that was because I hadn't approved it.  done! thanks!

**Comment by zlite** [comment]
I've created a schematic and PCB design for people who want to make their
own low-pass filter boards. It's here
<http://123d.circuits.io/circuits/514802-lidar-lite>.

On Mon, Jan 26, 2015 at 7:12 PM, Randy Mackay <notifications@github.com>
wrote:

> Ah, sorry, that was because I hadn't approved it. done! thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/diydrones/ardupilot-wiki-issue-tracker/issues/21#issuecomment-71583134>
> .
>



-- 
Chris Anderson
CEO, 3D Robotics
chris@3drobotics.com

**Comment by hamishwillee** [comment]
Hi Chris

Do you think it is worth adding this to the page?

For example replace the text:
"*Note: The capacitors shown in the diagram are required for first
generation hardware (as available Jan 2015). These should not be required
in later versions of the LIDAR Lite (at which point the diagram will change
to this
<http://planner.ardupilot.com/wp-content/uploads/sites/5/2014/08/RangeFinder_LIDARLite_Pixhawk_v2.png>
and
will have this circuit diagram
<http://planner.ardupilot.com/wp-content/uploads/sites/5/2014/08/LIDAR-LitePixhawkConnectionCircuitDiagram.png>.*
"
with
"*Note: The low pass filter shown in the diagram is required for first
generation hardware (as available Jan 2015) - a schematic and PCB design
are provided here <http://123d.circuits.io/circuits/514802-lidar-lite>.
These should not be required in later versions of the LIDAR Lite (at which
point the diagram will change to this
<http://planner.ardupilot.com/wp-content/uploads/sites/5/2014/08/RangeFinder_LIDARLite_Pixhawk_v2.png>
and
will have this circuit diagram
<http://planner.ardupilot.com/wp-content/uploads/sites/5/2014/08/LIDAR-LitePixhawkConnectionCircuitDiagram.png>.*
"

in
http://planner.ardupilot.com/wiki/common-rangefinder-lidarlite/#Connecting_to_the_Pixhawk

Regards
H

**Comment by zlite** [comment]
There's probably no harm in adding it as you suggest now. Later on, once
the module has been updated with these filters built-in, we can delete it.

Thanks!

Chris

On Mon, Jan 26, 2015 at 8:30 PM, Hamish Willee <notifications@github.com>
wrote:

> Hi Chris
>
> Do you think it is worth adding this to the page?
>
> For example replace the text:
> "*Note: The capacitors shown in the diagram are required for first
> generation hardware (as available Jan 2015). These should not be required
> in later versions of the LIDAR Lite (at which point the diagram will
> change
> to this
> <
> http://planner.ardupilot.com/wp-content/uploads/sites/5/2014/08/RangeFinder_LIDARLite_Pixhawk_v2.png>
>
> and
> will have this circuit diagram
> <
> http://planner.ardupilot.com/wp-content/uploads/sites/5/2014/08/LIDAR-LitePixhawkConnectionCircuitDiagram.png>.*
>
> "
> with
> "*Note: The low pass filter shown in the diagram is required for first
> generation hardware (as available Jan 2015) - a schematic and PCB design
> are provided here <http://123d.circuits.io/circuits/514802-lidar-lite>.
> These should not be required in later versions of the LIDAR Lite (at which
> point the diagram will change to this
> <
> http://planner.ardupilot.com/wp-content/uploads/sites/5/2014/08/RangeFinder_LIDARLite_Pixhawk_v2.png>
>
> and
> will have this circuit diagram
> <
> http://planner.ardupilot.com/wp-content/uploads/sites/5/2014/08/LIDAR-LitePixhawkConnectionCircuitDiagram.png>.*
>
> "
>
> in
>
> http://planner.ardupilot.com/wiki/common-rangefinder-lidarlite/#Connecting_to_the_Pixhawk
>
> Regards
> H
>
> On Tue, Jan 27, 2015 at 2:49 PM, Chris Anderson <notifications@github.com>
>
> wrote:
>
> > I've created a schematic and PCB design for people who want to make
> their
> > own low-pass filter boards. It's here
> > <http://123d.circuits.io/circuits/514802-lidar-lite>.
> >
> > On Mon, Jan 26, 2015 at 7:12 PM, Randy Mackay <notifications@github.com>
>
> > wrote:
> >
> > > Ah, sorry, that was because I hadn't approved it. done! thanks!
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/diydrones/ardupilot-wiki-issue-tracker/issues/21#issuecomment-71583134>
>
> >
> > > .
> > >
> >
> >
> >
> > --
> > Chris Anderson
> > CEO, 3D Robotics
> > chris@3drobotics.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/diydrones/ardupilot-wiki-issue-tracker/issues/21#issuecomment-71585625>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/diydrones/ardupilot-wiki-issue-tracker/issues/21#issuecomment-71588250>
> .
>



-- 
Chris Anderson
CEO, 3D Robotics
chris@3drobotics.com

**Comment by hamishwillee** [comment]
Thanks! Done (pushed live - no review needed)
