### ISSUE TITLE
Don't forget to mention python-dev

### ISSUE THREAD

**Issue by petershine** [diydrones/ardupilot-wiki-issue-tracker#212]
In section **Installing and configuring MavProxy** of page http://dev.ardupilot.com/wiki/making-a-mavlink-wifi-bridge-using-the-raspberry-pi/

Necessary modules needed before installing `droneapi` were mentioned. However, without `python-dev`, the following `sudo pip install droneapi` command will fail.

Maybe it was a common sense need not to be mentioned, but I think it can be helpful to those new to Python.

**Comment by hamishwillee** [comment]
Thanks very much Peter.

I've updated the section to explain how to install MAVProxy (not droneapi) and also link to the official installation instructions.

While it might make sense to install dronekit, this no longer has MAVPRoxy as a dependency. 

Setting this as close.
