### ISSUE TITLE
Learning ArduPilot – UARTs and the Console

### ISSUE THREAD

**Issue by franciscoflaum** [diydrones/ardupilot-wiki-issue-tracker#213]
[Learning ArduPilot – UARTs and the Console](http://dev.ardupilot.com/wiki/learning-ardupilot-uarts-and-the-console/) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant

**Comment by hamishwillee** [comment]
Closing - no suggestion provided.
