### ISSUE TITLE
Start up Failed to error, LED of solid red and unfamiliar tone buzzer

### ISSUE THREAD

**Issue by IndustrialWasteWeaponOfUltimate** [diydrones/ardupilot-wiki-issue-tracker#220]
hello,
I can't resolved error, help me.
I use Pixhawk, led of solid red and buzzer of high-low-low tone after power activation.
I start normally occasionally, flight normally. but I must have a long time to reach up there.
I think SDcard error, but don't SOS tone. Exchange to SDcard, not change anything.
Firmware override, it was not improved.

**Comment by hamishwillee** [comment]
Please raise technical support questions on the APM forums. This area is for feedback and suggestions on documentation.
