### ISSUE TITLE
Motor stepper for steering in APM rover

### ISSUE THREAD

**Issue by danferta** [diydrones/ardupilot-wiki-issue-tracker#222]
I want to install the APM rover in my tractor, but I have a problem with the steer motor. I think that is good to remplace the servo for a stepper motor, because with a servo is very difficult to move the tractor steering.

First, I try to read the Pulse signal that Ardupilot send at steering servo motor. I use for this purpose other Arduino and the function "PulseIn", and transform this pulse in a good value for the driver of the motor stepper. It works more or less, but the function "pulseIn" have a small error. Consequently, the stepper motor position have a little vibrates.

The good option, I think that is to find this pulse value directly in the main program ardupilot rover, but this is very difficult for me, and I can't to find it.

I need for help to search this value and add in the main program the C++ code to controle the stepper motor.

Thank you very much

Best regards

**Comment by hamishwillee** [comment]
@danferta This area is primarily for feedback on the docs. This question is technical support - can you please raise on the APM forums?
