### ISSUE TITLE
Building for Bebop on Linux: Change recommended compiler

### ISSUE THREAD

**Issue by djnugent** [diydrones/ardupilot-wiki-issue-tracker#223]
[Building for Bebop on Linux](http://dev.ardupilot.com/wiki/building-for-bebop-on-linux/) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant

Steps 1-3 on **Building Arducopter for Bebop** should be replaced with `sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf`. Discussed in https://github.com/diydrones/ardupilot/issues/3208 

@jberaud can you confirm this change

**Comment by hamishwillee** [comment]
Julien made this update. I have published.
