### ISSUE TITLE
Building for Bebop on Linux: Recovery Tip

### ISSUE THREAD

**Issue by djnugent** [diydrones/ardupilot-wiki-issue-tracker#224]
[Building for Bebop on Linux](http://dev.ardupilot.com/wiki/building-for-bebop-on-linux/) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant

Tip for **Recovery**:
If you are getting a read-only file system error while trying to restore your rcS init file, then try running `mount -o remount,rw 'rootfs'` to make your file system writeable.

@jberaud is this reasonable?

**Comment by jberaud** [comment]
mount -o remount,rw /​
It's totally reasonable. I'll do that along with the toolchain issue.

Julien

**Comment by hamishwillee** [comment]
@jberaud I saw you made this change, and pressed publish.

The change is shown below:

![image](https://cloud.githubusercontent.com/assets/5368500/11326905/e52d4cae-91c9-11e5-8f88-36be0fa952c0.png)

This is a bit different than what @djnugent was suggesting - ie his was like a tip to address the specific case of recovery and specifies 'rootfs". Can you confirm it meets the requirement?

**Comment by jberaud** [comment]
@hamishwillee  It's exactly equivalent on the bebop. Thanks

**Comment by hamishwillee** [comment]
Great, then I am closing this.
