### ISSUE TITLE
"make sitl -j4" command returns fatal error!

### ISSUE THREAD

**Issue by pil0706** [diydrones/ardupilot-wiki-issue-tracker#229]
i followed all the directions "http://dev.ardupilot.com/wiki/sitl-native-on-windows/" here and i added "export PATH=$PATH:$HOME/ardupilot/Tools/autotest" to the end of .bashrc

![image](https://cloud.githubusercontent.com/assets/4505669/11372632/e33b1aa4-9311-11e5-8981-f032b34eccf9.png)

and i typed "make sitl -j4" and it returns...

![image](https://cloud.githubusercontent.com/assets/4505669/11372655/fdf6f246-9311-11e5-9d16-2c0143c86bb2.png)

there are some foreign languages but if you are the well trained you would be okay to understand what this tells to you.. (i have no idea what this means even in my mother language)

if you guys have had this kind of issue and solved, please let me know how to fix this..

**Comment by hamishwillee** [comment]
@pil0706 This channel is for issues with the documentation. I have verified this article personally against Windows 8.1 and Windows 10 (clean installation) so I know that it is the correct setup.

As I can't reproduce the problem (see #195 for another instance of the same problem) there is not much I can do to help. One suggestion is that you might have more luck building with Vagrant!

Please raise this request on the APM Forums, where more people with build expertise may be able to help you.

**Comment by pil0706** [comment]
@hamishwillee 
Hey, i've checked the #195 already. but maybe i was lost in somewhere. I will following #195 again see if it works

thanks for reply!

**Comment by hamishwillee** [comment]
@pil0706 #195 did not resolve the issue. It was closed because the documents worked in my test case. The right "next step" is to seek advice on the APM forums.

**Comment by pil0706** [comment]
Hey, it works now!

**Comment by hamishwillee** [comment]
Great. Closed.
