### ISSUE TITLE
common-Measuring Vibration - out of date warning can be removed

### ISSUE THREAD

**Issue by peterbarker** [diydrones/ardupilot-wiki-issue-tracker#230]
[common-Measuring Vibration](http://copter.ardupilot.com/wiki/common-measuring-vibration/) - there is a disclaimer on this page indicating the code is not yet live in the stable distribution which is out-of-date.

**Comment by hamishwillee** [comment]
@peterbarker So are the changes present in copter, rover, plane current stable releases?

**Comment by hamishwillee** [comment]
@gmorph There is a note against [common-Measuring Vibration](http://copter.ardupilot.com/wiki/common-measuring-vibration/) that says:

> At time of writing (27 July 2015), Copter-3.3 is still a release candidate. Its changes are not yet present the official release of Copter, Plane and Rover. The changes here are expected to be in the next release of Plane and Rover.

Did the changes go into Plane/Rover? If so, what version?

**Comment by gmorph** [comment]
The changes are in Plane 3.4.
I haven't done a new release of Rover yet so its still not available.

Thanks, Grant.

**Comment by hamishwillee** [comment]
Thanks @gmorph. I've updated note as shown:

![image](https://cloud.githubusercontent.com/assets/5368500/11412429/22798780-9431-11e5-8381-fcbc6416708a.png)

Closing - now done.
