### ISSUE TITLE
make sitl  error on Cygwin

### ISSUE THREAD

**Issue by uri200** [diydrones/ardupilot-wiki-issue-tracker#236]
Hello,
I am trying to build AurduCopter at CygWin and I am getting ArduCopter.elf' failed when i try toi execute make sitl -j4. Any fix for this issue?
Thanks!!

Below you have the log

%% motors.o
%% Log.o
%% inertia.o
%% control_poshold.o
%% control_rtl.o
Building /tmp/ArduCopter.build/ArduCopter.elf
%% ArduCopter.elf
/tmp/ArduCopter.build/libraries/DataFlash/LogFile.o: In function `ZN15DataFlash_Class20Log_Write_ParametersEv':
/home/uri/ardupilot/libraries/DataFlash/LogFile.cpp:718: undefined reference to `DataFlash_Class::Log_Write_Parameter(AP_Param const*, AP_Param::ParamToken const&, ap_var_type)'
/home/uri/ardupilot/libraries/DataFlash/LogFile.cpp:718: undefined reference to `DataFlash_Class::Log_Write_Parameter(AP_Param const*, AP_Param::ParamToken const&, ap_var_type)'
collect2: error: ld returned 1 exit status
C:/cygwin/home/uri/ardupilot/mk/board_native.mk:106: recipe for target '/tmp/ArduCopter.build/ArduCopter.elf' failed
make: *** [/tmp/ArduCopter.build/ArduCopter.elf] Error 1

**Comment by hamishwillee** [comment]
That looks like a "real" error in the build rather than an error in the docs for the build process. Can you please re-raise on the APM forums or in the ardupilot (source code) wiki.

I am closing this. Thanks for taking the time to post!

**Comment by uri200** [comment]
Thanks. 
I did 
http://ardupilot.com/forum/viewtopic.php?f=69&t=14489&sid=1b16920190f4cc17e55c0873cf6c02a4
