### ISSUE TITLE
Use of servo or DC stepper motors with no position feedback

### ISSUE THREAD

**Issue by raptortrias** [diydrones/ardupilot-wiki-issue-tracker#239]
Hi,

 Is the use of motors with no position feedback supported in antenna tracker. Since the pixhawk has all the sensors it should be possible to use it for orientation of the antenna. I am looking to integrate heavy duty stepper motors that lack position feedback

[Configuration](http://antennatracker.ardupilot.com/wiki/configuration/) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant

**Comment by hamishwillee** [comment]
Hi @raptortrias 

This tracker is for issues with the documentation. Please raise this technical support query on the APM forums (link at bottom of any wiki page)

Regards
Hamish

**Comment by rmackay9** [comment]
@raptortrias, yes, that should work i think.
