### ISSUE TITLE
Installing APM Planner for Mac

### ISSUE THREAD

**Issue by KTCproductions** [diydrones/ardupilot-wiki-issue-tracker#250]
[Installing APM Planner for Mac](http://planner2.ardupilot.com/wiki/mac-install/) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant

Hi, 

for some reason the APM planner is not working fully on my mac, i have installed the FTDIUSBSerialDriver_10_4_10_5_10_6_10_7.pkg yet still do not get the option to change from the Bluetooth-Incoming-port to the usbmodem521, nor do my maps load.

Please do advise me how to fix this issue. Would it maybe be better/easier to run Bootcamp/parallel (do not like parallel) in order to run these programs on my mac?

**Comment by hamishwillee** [comment]
@KTCproductions This area is primarily for documentation issues. The best place to ask technical  support questions is [the forums](http://ardupilot.com/forum/viewforum.php?f=82&sid=485f7dbb1db0849e2d1c5694ea6ec9a8). There are some USB connectivity issues [already posted](http://ardupilot.com/forum/viewtopic.php?f=82&t=13078)

I would say that if you are required to install additional software not mentioned in the documentation (e.g. bootcamp or whatever) that is an issue - in which case please reopen this issue with the flaw in the docs you discovered.
