### ISSUE TITLE
Flying with a Joystick/Gamepad

### ISSUE THREAD

**Issue by clemtrinc** [diydrones/ardupilot-wiki-issue-tracker#255]
[Flying with a Joystick/Gamepad](http://copter.ardupilot.com/wiki/flying-with-a-joystickgamepad-instead-of-rc-controller/) - No failover to transmitter if the usb joystick is disconnected from the usb port, or if I cut the telemetry link, I followed the exact procedure from the page, this was tested 6 motnhs ago, and again today after 2 updates of mission planner, on both a apm and pixhawk.

**Comment by hamishwillee** [comment]
I *think* that the instructions are correct, so if this doesn't work it is probably a bug in ardupilot itself. I have therefore re-posted as https://github.com/diydrones/ardupilot/issues/3389

**Comment by clemtrinc** [comment]
Alright thanks, sorry for the mistake I'm new to this community

**Comment by hamishwillee** [comment]
@clemtrinc Seriously, not a problem. It is possible this is a documentation problem - but the core team will know for sure.

**Comment by CraigElder** [comment]
@clemtrinc Please post a log file showing the issue. Thanks

**Comment by clemtrinc** [comment]
Alright, I can't do this until next week as I'm out of town, but I'll do
this first thing.
