### ISSUE TITLE
common-Pixhawk Overview

### ISSUE THREAD

**Issue by lvale** [diydrones/ardupilot-wiki-issue-tracker#260]
The last sentence of this paragraph about Virtual Pin 103 is not correct, because SBUS out is now implemented and controlled by a parameter 

http://copter.ardupilot.com/wiki/arducopter-parameters/#enable_use_of_sbus_output_brd_sbus_out

Virtual Pin 103: RSSI (Received Signal Strength Input) input pin voltage (SBus connector output pin). This is the voltage measured by the RSSI input pin on the SBUS-out connector (the bottom pin of the 2nd last servo connector on the 14 connector servo rail). **Can alternatively serve as SBus out but not yet implemented.**

**Comment by hamishwillee** [comment]
Thanks @lvale. I've updated [the text](http://planner.ardupilot.com/wiki/common-pixhawk-overview/#pixhawk_analog_input_pins) to look like this - OK?

![image](https://cloud.githubusercontent.com/assets/5368500/12412706/e7ad1a6e-bedc-11e5-811c-537f9e6ea4bf.png)

**Comment by lvale** [comment]
Perfect @hamishwillee 
Thanks
