### ISSUE TITLE
Mission Planner Language Translations

### ISSUE THREAD

**Issue by robetyosua** [diydrones/ardupilot-wiki-issue-tracker#261]
i just finished translate into bahasa indonesia, i hope you can implement this language on mission planner. thank you
[translation.zip](https://github.com/diydrones/ardupilot-wiki-issue-tracker/files/82799/translation.zip)

**Comment by hamishwillee** [comment]
Hi @robetyosua 

Thanks very much. Can you please repost these on the Mission Planner issue tracker here: https://github.com/diydrones/MissionPlanner/issues ?

This area is for issues with the wiki and its content.

I am closing.

Regards
Hamish

**Comment by robetyosua** [comment]
ok sorry @hamishwillee  , I 've repost my request here : https://github.com/diydrones/MissionPlanner/issues 
Thanks @hamishwillee 

regards,

Robet

**Comment by hamishwillee** [comment]
@robetyosua  No need to be sorry - thanks for your contribution :-) !!!
