### ISSUE TITLE
Setting up SITL on Linux. Load a mission.

### ISSUE THREAD

**Issue by approximator** [diydrones/ardupilot-wiki-issue-tracker#263]
[Setting up SITL on Linux](http://dev.ardupilot.com/wiki/setting-up-sitl-on-linux/)

In section **Load a mission** command
```
wp load ../Tools/autotest/Plane-Missions/CMAC-toff-loop.txt
```

should be changed to 
```
wp load ../Tools/autotest/ArduPlane-Missions/CMAC-toff-loop.txt
```

as there is no **Plane-Missions** directory in autotest.

**Comment by hamishwillee** [comment]
Fixed. Thank you very much.
