### ISSUE TITLE
interfacing GoPro hero 4 session camera with odroid C1 board

### ISSUE THREAD

**Issue by aman-IoT** [diydrones/ardupilot-wiki-issue-tracker#264]
My aim is to do live image processing using odroid C1 board from the live recording from camera and instruct drone the path to follow

I have 3DR Iris drone
GoPro hero 4 session camera
Hero 3 Gimbal 
Odroid C1 board

So how can I interface odroid C1 to hero 4 session camera {has only bluetooth, wifi, micro USB, SD }  support

Please help ASAP

**Comment by rmackay9** [comment]
This issue tracker is really to request changes to the ardupilot wiki.  Technical questions should go somewhere else although the question you're asking isn't something we current do within ardupilot so I at least don't know the answer.
