### ISSUE TITLE
Add Leonard to Commercial Support

### ISSUE THREAD

**Issue by lthall** [diydrones/ardupilot-wiki-issue-tracker#266]
Leonard Hall

Contact: Leonard Hall
Email: leonardthall@gmail.com

Capabilities:

Multirotor Tuning
Airframe design and performance optimisation
Navigation and attitude controller features
Flight mode design and implementation
Troubleshooting and support (log review, vehicle support)

**Comment by hamishwillee** [comment]
@lthall - [added here](http://planner.ardupilot.com/wiki/common-commercial-support/#leonard_hall). You might want to add geographical location and other contact details if that is relevant. 

Closing.
