### ISSUE TITLE
QGroundControl information is out of data

### ISSUE THREAD

**Issue by DonLakeFlyer** [diydrones/ardupilot-wiki-issue-tracker#276]
[common-Choosing a Ground Station](http://copter.ardupilot.com/wiki/common-choosing-a-ground-station/) - 

Full support for ArduPilot firmware vehicles in QGroundControl is now in beta. This includes full Setup and Configuration, Mission Planning, Flight Display as well as streaming video. Also QGroundControl is now supported an Android Tablet.

The Beta link in here: http://www.qgroundcontrol.org/apm
Download link: http://www.qgroundcontrol.org/downloads
Wiki: Should link to qgrouncontrol.org no to a deeper page
Support forum: https://groups.google.com/forum/#!forum/qgroundcontrol
Gitter: https://gitter.im/mavlink/qgroundcontrol

**Comment by hamishwillee** [comment]
Thanks @DonLakeFlyer! I've updated the page as you indicated!

**Comment by DonLakeFlyer** [comment]
Awesome, big thanks Hamish

**Comment by DonLakeFlyer** [comment]
Just realized I should have provided you with a new image as well. Here is a good one. Sorry about that.

![tabletfly](https://cloud.githubusercontent.com/assets/5876851/12501024/92fa0454-c06d-11e5-9839-914fe39de0f5.jpg)

**Comment by hamishwillee** [comment]
Thanks Don - I added that now.
