### ISSUE TITLE
Arduplane 3.5.0

### ISSUE THREAD

**Issue by JeyPi** [diydrones/ardupilot-wiki-issue-tracker#283]
Pixhawk Arduplane 3.5.0
After Acc and compass calibration.
The delta wing flies perfectly, but would not fly AUTO. It RTL nicely though.
It always loiter around the first waypoint on the route.
Help needed
[Telemetry](https://www.dropbox.com/s/nqmjqglkhesjsmq/1.BIN?dl=0)

**Comment by hamishwillee** [comment]
Please raise this on the [forums](http://ardupilot.com/forum/). This issue tracker is for errors in the documentation.
