### ISSUE TITLE
add Pixracer to common-autopilot's page

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot-wiki-issue-tracker#288]
http://copter.ardupilot.com/wiki/common-autopilots/

Most of the information can be found on these pages I think:
https://pixhawk.org/modules/pixracer
http://auav.com/

**Comment by hamishwillee** [comment]
@rmackay9  OK, I have created the [draft here](http://planner.ardupilot.com/wiki/common-pixracer-overview/). It copies a lot from the pages you link.

Please let me know whether it is OK, or provide "enhancement suggestions".

Note that it is marked as under construction. That can go when you're happy with it.

**Comment by hamishwillee** [comment]
Also, what should we say in http://planner.ardupilot.com/wiki/common-autopilots/common-choosing-a-flight-controller/ ?

Is it worth talking about this board yet? How would it fit into our "scale of recommendations"?

**Comment by rmackay9** [comment]
Thanks very much Hamish!
I've made a minor change to highlight that it has only 6 pwm outputs.  That's the key limitation that allows it to be so small.
On the common-choosing-a-flight-controller page I think we should recommend it for small frames (i.e. 250 racing quads) that require no more than 6 pwm outputs.

**Comment by hamishwillee** [comment]
Good change. I've removed the under construction warning, so this job is now done.

I added the recommendation you suggested to common-choosing-a-flight-controller - thanks!

Cheerio. Closing. H
