### ISSUE TITLE
SingleCopter and CoaxCopter

### ISSUE THREAD

**Issue by suranthiran** [diydrones/ardupilot-wiki-issue-tracker#301]
I am trying to use pixracer with APM Ardupilot to run my coaxial helicopter. The coaxial motors respond to throttle and yaw commands correctly. But, the servos do not seem to respond, I tested the same code with pixhawk previously and it worked like charm. I am having trouble to make the servos run with pixracer. I appreciate any help or suggestion.

**Comment by hamishwillee** [comment]
I suggest you raise this issue on the APM forums. This area is for questions about the wiki documentation.
