### ISSUE TITLE
Copter Mission Command List - max climbing speed

### ISSUE THREAD

**Issue by gaucho1978** [diydrones/ardupilot-wiki-issue-tracker#304]
[Copter Mission Command List](http://copter.ardupilot.com/wiki/mission-command-list/) - 
We need to move the copter at 8m/s but the maximum speed on the mission planner seems to be lower. is it correct? could we achieve a bigger value for the speed?

**Comment by magicrub** [comment]
This is not a wiki bug/feature, it's a flight controller issue. Please repost there: https://github.com/diydrones/ardupilot/issues/new

Please specify which command you're having trouble with.

**Comment by gaucho1978** [comment]
ok. thank you.
