### ISSUE TITLE
add commercial support page to menu of ardupilot.com

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot-wiki-issue-tracker#306]
We should add the commercial support page to the ardupilot.com menu under Community.   It looks like it's already there for all the individual vehicles.  So just missing on the one ardupilot.com site.

http://planner.ardupilot.com/wiki/common-commercial-support

**Comment by hamishwillee** [comment]
This has been done. The link actually goes to the mission planner version.

**Comment by rmackay9** [comment]
ok, great thanks!
