### ISSUE TITLE
QuadPlane Support

### ISSUE THREAD

**Issue by raptortrias** [diydrones/ardupilot-wiki-issue-tracker#311]
[QuadPlane Support](http://plane.ardupilot.com/wiki/quadplane-support/) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant

Considering an alternative setup where the two front motors are used in both QUAD configuration and FIXED wing configuration.

 Is it possible to map output for twin in fixed wing and 2 of the 4 for quad as the same motors.

 Would use servo controlled tilt to transition from the 2 front motors from quad configuration (facing up) to forward movement in fixed wing?

 Thanks

**Comment by hamishwillee** [comment]
This is not the right place to ask technical questions - check out the APM forums. This is for issues with wiki content.

Closing. Regards H
