### ISSUE TITLE
add dev page on firmware binary bisection search

### ISSUE THREAD

**Issue by tridge** [diydrones/ardupilot-wiki-issue-tracker#40]
See for example this discussion between me and MarkM
http://diydrones.com/profiles/blog/show?id=705844%3ABlogPost%3A1899907&xg_source=activity&page=3#comments

**Comment by hamishwillee** [comment]
@tridge Done. Would appreciate your review - [Finding the Particular Commit which Introduced a Bug](http://dev.ardupilot.com/wiki/finding-the-particular-commit-which-introduced-a-bug/). I am not completely convinced by the title, but it is better than Firmware Binary Bisection Search which doesn't tell readers what the topic is about ... unless they already know.

**Comment by hamishwillee** [comment]
Tridge has said this is OK.
