### ISSUE TITLE
Pixhawk wiring should should be split into common and then vehicle specifics

### ISSUE THREAD

**Issue by gmorph** [diydrones/ardupilot-wiki-issue-tracker#48]
In 
http://rover.ardupilot.com/wiki/pixhawk-wiring-rover/ 
and
http://rover.ardupilot.com/wiki/common-pixhawk-wiring-and-quick-start/

The first half of each page is common (the same) and should be separated out into a common page.  This should also be done for PX4 and APM2 wiring.

Then a vehicle specific page should be created highlighting the differences required for each vehicle.

**Comment by hamishwillee** [comment]
Closing.

This was addressed. The first article was deleted. The second was modified so that the [vehicle specific parts](http://rover.ardupilot.com/wiki/common-pixhawk-wiring-and-quick-start/#connect_motors) are displayed in a wiki-specific way.
