### ISSUE TITLE
Config files for common airframes has 2 pages and they need to be merged

### ISSUE THREAD

**Issue by gmorph** [diydrones/ardupilot-wiki-issue-tracker#49]
These two pages need to be merged back into the first page.

http://plane.ardupilot.com/wiki/flying/tuning/configuration-files-for-common-airframes/
http://plane.ardupilot.com/wiki/configuration-files-for-common-airframes-2/

**Comment by hamishwillee** [comment]
I merged the articles some weeks ago (and just did another minor update). See http://plane.ardupilot.com/wiki/flying/configuration-files-for-common-airframes/

This is therefore closed.
