### ISSUE TITLE
Fix inconsistent Ardu/APM branding in wiki text

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/ardupilot-wiki-issue-tracker#82]
The following changes will be made to reflect our autopilot branding:

* Change all instances of APM:Pilot to ArduPilot
* Change all instances of APM:Copter and ArduCopter to "Copter"
* Change all instances of APM:Plane and ArduPlane to "Plane"
* Change all instances of APM:Rover and ArduRover to "Rover"
* AntennaTracker referred to as "Antenna Tracker" (TBD)

The official name of copter/rover/plane is still APM:Copter (etc) but this will only be used in the rare cases it is needed (e.g. referring to the platforms outside of the site). 

Note:
* Changing instances where ArduPilot is referred to as APM cannot be automated, and those changes will have to be made on an ad-hoc basis.

**Comment by rmackay9** [comment]
Maybe just shorten AntennaTracker to just Tracker.

**Comment by CraigElder** [comment]
Also please ensure that the capitalization of ArduPilot is consistent throughout the wiki.

**Comment by hamishwillee** [comment]
Will do my best!

**Comment by hamishwillee** [comment]
What are official names for "Mission Planner" and "APM Mission Planner 2"  going to be?

**Comment by gmorph** [comment]
We haven't discussed changing the names for those.  The respective
maintainers would need to be involved which hasn't been arranged so they
will remain un-touched for the moment.

Thanks, Grant.

On 10 April 2015 at 10:50, Hamish Willee <notifications@github.com> wrote:

> What are official names for "Mission Planner" and "APM Mission Planner 2"
> going to be?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/diydrones/ardupilot-wiki-issue-tracker/issues/82#issuecomment-91390909>
> .
>



-- 
Thanks

Grant

**Comment by hamishwillee** [comment]
Possible problem pages

* http://rover.ardupilot.com/wiki/apmrover2-parameters/ - name may be hard linked in auto scripts

**Comment by hamishwillee** [comment]
This is done. I will reply with respect to "limitations" on the ardu wiki editors group.
