### ISSUE TITLE
Add Zubax GPS docs

### ISSUE THREAD

**Issue by CraigElder** [diydrones/ardupilot-wiki-issue-tracker#84]
http://docs.zubax.com/Zubax_GNSS_tutorial:_Using_with_Pixhawk#Configuring_Pixhawk_with_APM_firmware

**Comment by hamishwillee** [comment]
I have reproduced this on the wiki as [Zubax GNSS Positioning Module — GPS, Compass and Barometer](http://rover.ardupilot.com/wiki/other-project-and-common-topics/common-optional-hardware/common-positioning-landing-page/common-zubax-gnss-positioning-module-gps-compass-and-barometer/). It is almost the same, but slightly restructured.

I am never sure what exactly to include when there is a good set of documentation on a vendor wiki - on one hand it is good to have the information on ardupilot in case vendor wiki goes down, but on the downside it does mean that the ardupilot version can get out of date. In this case I decided to include the information from Pavel's wiki but I have put a prominent TIP near the top providing links back.

Pavel, do you think you can keep the ArduPilot version updated on this wiki too? If not, Craig, do you think we might be best off just having my overview, and forcing people to go to Pavel's site for all "real" information?
