### ISSUE TITLE
Add Serial Connection instructions

### ISSUE THREAD

**Issue by zlite** [diydrones/ardupilot-wiki-issue-tracker#90]
On the Running the Examples page (http://python.dronekit.io/examples/running_examples.html) , we include many connection options, but not Serial, such as with RaspberryPi. 

Let's add:

*Linux Computer Connected to the Vehicle Via Serial (RaspberryPi example shown)*

mavproxy.py --master=/dev/ttyAMA0 --baudrate 57600

**Comment by hamishwillee** [comment]
Excellent idea. I haven't verified the information personally but I see no reason not to trust you and the docs on the [wiki](http://dev.ardupilot.com/wiki/companion-computers/raspberry-pi-via-mavlink/#testing_the_connection). Thanks.

Closing now. This has been added as part of [this pull request](https://github.com/diydrones/dronekit-python/pull/94).
