### ISSUE TITLE
ArduCopter 'LEDs (Pixhawk/PX4)' doesn't contain solid red

### ISSUE THREAD

**Issue by SkiTiSu** [diydrones/ardupilot-wiki-issue-tracker#97]
Solid red with "Beep Beep Beep    Beep-- Beep-- Beep--" means there're some problems with SD card (not inserted, bad format, etc)

Thanks.

**Comment by hamishwillee** [comment]
Thank you very much. I have added the information to  [LEDs (Pixhawk/PX4)](http://planner.ardupilot.com/wiki/other-project-and-common-topics/common-autopilots/common-pixhawk-overview/common-leds-pixhawk/) along with a link to the associated Sound files.
